version: "3.5"

services:
  db:
    image: mysql
    volumes:
      - "./volume/mysql:/var/lib/mysql"
      - "./compose/mysql/init:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    ports:
      - 3300:3306
    networks:
      app50_net:
        ipv4_address: 172.50.0.2

  app:
    image: node:18-bullseye
    #build: ./compose/app
    environment:
      - TZ=Aisa/Tokyo
    ports:
      - 3001:3000
    volumes:
      - ./volume/app:/home/node/app
    command: /bin/bash 
    tty: true
    networks:
      app50_net:
        ipv4_address: 172.50.0.3

  client:
    build: ./compose/client
    #image: ubuntu
    command: /bin/bash
    tty: true
    networks:
        app50_net:
          ipv4_address: 172.50.0.4

networks:
  app50_net:
    name: app50_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.50.0.0/24
